"""empty message

Revision ID: 67e81f188b0b
Revises: 3e7434763b35
Create Date: 2024-09-12 21:59:06.766405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e81f188b0b'
down_revision = '3e7434763b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_expiration')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
